package com.example.domain.pdf

import android.content.Context
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import java.io.File
import java.io.FileOutputStream

object SamplePdfGenerator {
    fun createSamplePdf(context: Context): File {
        val outputFile = File(context.cacheDir, "Infinity_PDF_Sample_Report.pdf")
        if (outputFile.exists() && outputFile.length() > 1000) {
            return outputFile
        }

        val document = PdfDocument()
        val paint = Paint().apply { isAntiAlias = true }

        // --- PAGE 1: Title & Executive Summary ---
        val pageInfo1 = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 at 72dpi
        val page1 = document.startPage(pageInfo1)
        val canvas1 = page1.canvas

        // Header Background
        paint.color = Color.rgb(30, 58, 138) // Deep Blue
        canvas1.drawRect(0f, 0f, 595f, 130f, paint)

        // Title
        paint.color = Color.WHITE
        paint.textSize = 26f
        paint.isFakeBoldText = true
        canvas1.drawText("Infinity PDF Sample Report", 40f, 60f, paint)

        // Subtitle
        paint.textSize = 14f
        paint.isFakeBoldText = false
        paint.color = Color.rgb(224, 231, 255)
        canvas1.drawText("Quarterly Business & Document Intelligence Overview", 40f, 90f, paint)

        // Accent Line
        paint.color = Color.rgb(59, 130, 246)
        paint.strokeWidth = 3f
        canvas1.drawLine(40f, 115f, 555f, 115f, paint)

        // Section 1: Executive Summary
        paint.color = Color.rgb(17, 24, 39)
        paint.textSize = 18f
        paint.isFakeBoldText = true
        canvas1.drawText("1. Executive Summary", 40f, 170f, paint)

        paint.textSize = 12f
        paint.isFakeBoldText = false
        paint.color = Color.rgb(55, 65, 81)
        val summaryLines = listOf(
            "This document is a sample multi-page business report generated by Infinity PDF.",
            "You can use it to test and demonstrate all built-in features including Compression,",
            "Merging, Splitting, Page Rotation, OCR, Conversion to Word/Excel, Watermarking,",
            "Page Numbering, Annotation, Signing, and Encryption.",
            "",
            "Key Performance Indicators (KPIs) showed steady growth of +24.8% quarter-over-quarter,",
            "driven by enterprise adoption of smart document workflow automation."
        )
        var yPos = 200f
        for (line in summaryLines) {
            canvas1.drawText(line, 40f, yPos, paint)
            yPos += 20f
        }

        // Feature Highlight Cards
        yPos += 20f
        paint.color = Color.rgb(239, 246, 255)
        canvas1.drawRoundRect(40f, yPos, 280f, yPos + 100f, 12f, 12f, paint)
        canvas1.drawRoundRect(315f, yPos, 555f, yPos + 100f, 12f, 12f, paint)

        paint.color = Color.rgb(30, 58, 138)
        paint.textSize = 14f
        paint.isFakeBoldText = true
        canvas1.drawText("Smart Compression", 55f, yPos + 35f, paint)
        canvas1.drawText("Document Security", 330f, yPos + 35f, paint)

        paint.color = Color.rgb(75, 85, 99)
        paint.textSize = 10f
        paint.isFakeBoldText = false
        canvas1.drawText("Reduces size up to 80% while", 55f, yPos + 60f, paint)
        canvas1.drawText("maintaining crystal clear text.", 55f, yPos + 75f, paint)

        canvas1.drawText("Password protection & 256-bit", 330f, yPos + 60f, paint)
        canvas1.drawText("encryption for confidential files.", 330f, yPos + 75f, paint)

        // Section 2: Financial Summary Table
        yPos += 140f
        paint.color = Color.rgb(17, 24, 39)
        paint.textSize = 16f
        paint.isFakeBoldText = true
        canvas1.drawText("2. Quarterly Financial Summary", 40f, yPos, paint)

        yPos += 25f
        // Table Header
        paint.color = Color.rgb(243, 244, 246)
        canvas1.drawRect(40f, yPos, 555f, yPos + 28f, paint)

        paint.color = Color.rgb(31, 41, 55)
        paint.textSize = 11f
        paint.isFakeBoldText = true
        canvas1.drawText("Department", 50f, yPos + 18f, paint)
        canvas1.drawText("Q1 Budget", 200f, yPos + 18f, paint)
        canvas1.drawText("Q2 Actual", 320f, yPos + 18f, paint)
        canvas1.drawText("Variance (%)", 450f, yPos + 18f, paint)

        val tableRows = listOf(
            Triple("Engineering", "$420,000", "+4.2%"),
            Triple("Product Design", "$165,000", "-2.1%"),
            Triple("Marketing & Sales", "$310,000", "+8.5%"),
            Triple("Operations & Legal", "$180,000", "+0.8%"),
            Triple("Total Enterprise", "$1,075,000", "+3.7%")
        )

        yPos += 28f
        paint.isFakeBoldText = false
        for ((idx, row) in tableRows.withIndex()) {
            if (idx % 2 == 1) {
                paint.color = Color.rgb(249, 250, 251)
                canvas1.drawRect(40f, yPos, 555f, yPos + 24f, paint)
            }
            paint.color = if (idx == tableRows.size - 1) Color.rgb(17, 24, 39) else Color.rgb(55, 65, 81)
            if (idx == tableRows.size - 1) paint.isFakeBoldText = true

            canvas1.drawText(row.first, 50f, yPos + 16f, paint)
            canvas1.drawText(row.second, 200f, yPos + 16f, paint)
            canvas1.drawText(row.second, 320f, yPos + 16f, paint)
            canvas1.drawText(row.third, 450f, yPos + 16f, paint)
            yPos += 24f
        }

        // Footer Page 1
        paint.color = Color.rgb(156, 163, 175)
        paint.textSize = 9f
        paint.isFakeBoldText = false
        canvas1.drawText("Infinity PDF • Document Intelligence Engine", 40f, 810f, paint)
        canvas1.drawText("Page 1 of 2", 500f, 810f, paint)

        document.finishPage(page1)

        // --- PAGE 2: Action Plan & Authorization ---
        val pageInfo2 = PdfDocument.PageInfo.Builder(595, 842, 2).create()
        val page2 = document.startPage(pageInfo2)
        val canvas2 = page2.canvas

        // Header
        paint.color = Color.rgb(30, 58, 138)
        canvas2.drawRect(0f, 0f, 595f, 60f, paint)
        paint.color = Color.WHITE
        paint.textSize = 16f
        paint.isFakeBoldText = true
        canvas2.drawText("Infinity PDF Report • Section 3: Strategic Roadmap", 40f, 38f, paint)

        // Roadmap content
        yPos = 100f
        paint.color = Color.rgb(17, 24, 39)
        paint.textSize = 16f
        canvas2.drawText("3. Strategic Objectives for Q3 & Q4", 40f, yPos, paint)

        val objectives = listOf(
            "• Implement zero-latency mobile document scanning with automated perspective correction.",
            "• Expand format conversion support across Microsoft Office DOCX, XLSX, and PPTX standards.",
            "• Provide client-side AES 256-bit encryption ensuring zero document leakage.",
            "• Embed on-device machine learning OCR for rapid multi-language text digitization.",
            "• Enable real-time digital signature capture with cryptographic verification stamps."
        )

        yPos += 30f
        paint.textSize = 12f
        paint.isFakeBoldText = false
        paint.color = Color.rgb(55, 65, 81)
        for (obj in objectives) {
            canvas2.drawText(obj, 40f, yPos, paint)
            yPos += 35f
        }

        // Signature Authorization Block
        yPos += 50f
        paint.color = Color.rgb(243, 244, 246)
        canvas2.drawRoundRect(40f, yPos, 555f, yPos + 180f, 12f, 12f, paint)

        paint.color = Color.rgb(17, 24, 39)
        paint.textSize = 14f
        paint.isFakeBoldText = true
        canvas2.drawText("Document Approval & Sign-Off", 60f, yPos + 35f, paint)

        paint.color = Color.rgb(107, 114, 128)
        paint.textSize = 11f
        paint.isFakeBoldText = false
        canvas2.drawText("Authorized Representative Signature:", 60f, yPos + 70f, paint)

        // Signature Line
        paint.color = Color.rgb(209, 213, 219)
        paint.strokeWidth = 1.5f
        canvas2.drawLine(60f, yPos + 130f, 320f, yPos + 130f, paint)
        canvas2.drawLine(360f, yPos + 130f, 530f, yPos + 130f, paint)

        paint.color = Color.rgb(107, 114, 128)
        paint.textSize = 10f
        canvas2.drawText("Signature", 60f, yPos + 150f, paint)
        canvas2.drawText("Date", 360f, yPos + 150f, paint)

        // Footer Page 2
        paint.color = Color.rgb(156, 163, 175)
        paint.textSize = 9f
        canvas2.drawText("Infinity PDF • Generated for testing and preview", 40f, 810f, paint)
        canvas2.drawText("Page 2 of 2", 500f, 810f, paint)

        document.finishPage(page2)

        // Write to file
        FileOutputStream(outputFile).use { out ->
            document.writeTo(out)
        }
        document.close()

        return outputFile
    }
}
